Index: /Users/rams/Documents/workspace/ERDirectToWeb/Sources/er/directtoweb/components/numbers/ERD2WEditNumber.java
===================================================================
--- /Users/rams/Documents/workspace/ERDirectToWeb/Sources/er/directtoweb/components/numbers/ERD2WEditNumber.java	(revision 8419)
+++ /Users/rams/Documents/workspace/ERDirectToWeb/Sources/er/directtoweb/components/numbers/ERD2WEditNumber.java	(working copy)
@@ -60,7 +60,13 @@
                 throw ERXValidationFactory.defaultFactory().createException(object(), propertyKey(), anObject, "NotANumberException");
             }
         } catch(NSValidation.ValidationException ex) {
-            validationFailedWithException(ex, anObject, propertyKey());
+        	/* I'm not sure why this line is here but it is causing duplicate
+        	 * validation errors to show up in the page. Removing it seems to 
+        	 * fix the problem since throwing a validation exception sends it 
+        	 * through validationFailedWithException anyway. Perhaps this is 
+        	 * not the case in 5.3? I haven't checked.
+        	 */
+            //validationFailedWithException(ex, anObject, propertyKey());
             throw ex;
         }
         return super.validateTakeValueForKeyPath(convertNumber(number), propertyKey());
